image:
  - Visual Studio 2015
  - Visual Studio 2017

configuration:
  - Release

platform:
  - x64

install:
  # Python 3
  - cmd: set PATH=C:\Python34-x64;C:\Python34-x64\Scripts;%PATH%

  - cmd: pip install pipenv
  - cmd: pipenv install

  - git submodule update --init --recursive

build_script:
  - cmd: pipenv run scripts/build_deps.py windows
  - cmd: cmake . -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain/win.cmake
  - cmd: cmake --build . --target install --config release

